INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Mr. Chocolate",5,"M","Brown","Nice",1)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Rowdy",6,"M","Red-Brown","Energetic",1)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Tabitha",10,"F","Brown","Calm",1)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Sergeant Brown",16,"M","Dark Brown","Aggressive",0)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Melissa",8,"F","Red-Brown","Cheerful",0)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Grinch",7,"M","Brown","Grumpy",1)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES ("Wendy",12,"F","Dark Brown","Nice",1)
INSERT INTO bears(name, age, gender, color, temperament, alive) VALUES (NULL,4,"M","Brown","Man Eater",0)
